#include "../buildsteps/base.txt"

COMMENT(#,Define an image for building the 64bit manylinux wheels for Python)
FROM quay.io/pypa/manylinux1_x86_64


#include "../buildsteps/docker.maintainer.txt"


COMMENT(#,Install Cmake (either from source (reliable) or from yum (64-bit only and it does not symlink in a cmake executable)))
COMMENT(#,ALTERNATE: RUN yum install -y cmake28 && ln -s `which cmake28` /usr/local/bin/cmake)
COMMENT(#,ALTERNATE: RUN wget --no-check-certificate "http://www.cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz" && tar -zxvf cmake-2.8.12.2.tar.gz && cd cmake-2.8.12.2 && ./bootstrap && make && make install)
COMMENT(#,ALTERNATE: RUN yum remove -yt cmake && yum install -y cmake3 && cd /usr/bin && ln -s cmake3 cmake && ln -s ccmake3 ccmake && ln -s cpack3 cpack && ln -s ctest3 ctest)
COMMENT(#,ALTERNATE: RUN wget --no-check-certificate "https://www.cmake.org/files/v3.10/cmake-3.10.1.tar.gz" && tar -zxvf cmake-3.10.1.tar.gz && cd cmake-3.10.1 && ./bootstrap && gmake && gmake install)
COMMENT(#,ALTERNATE: RUN curl -LO "https://www.cmake.org/files/v3.12/cmake-3.12.0.tar.gz" && tar -zxf cmake-3.12.0.tar.gz && cd cmake-3.12.0 && ./bootstrap && gmake && gmake install)


RUN yum update -y && \
  yum install -y epel-release && \
  yum update -y && \
  yum clean all
  
RUN yum groupinstall -y "Development Tools" && \
  yum install -y git subversion mercurial && \
  yum install -y wget curl bzip2 && \
  yum clean all

RUN yum remove cmake; exit 0
RUN yum install -y cmake3 && \
  cd /usr/bin && \
  ln -s cmake3 cmake && \
  ln -s ccmake3 ccmake && \
  ln -s cpack3 cpack && \
  ln -s ctest3 ctest && \
  yum clean all


COMMENT(#,Install virtualenv into one of the python installations for creating other virtual environments)
RUN \
/opt/python/cp27-cp27m/bin/pip install virtualenv && \
/opt/python/cp27-cp27m/bin/virtualenv /py27   --python=/opt/python/cp27-cp27m/bin/python && \
/opt/python/cp27-cp27m/bin/virtualenv /py27mu --python=/opt/python/cp27-cp27mu/bin/python && \
/opt/python/cp27-cp27m/bin/virtualenv /py34   --python=/opt/python/cp34-cp34m/bin/python && \
/opt/python/cp27-cp27m/bin/virtualenv /py35   --python=/opt/python/cp35-cp35m/bin/python && \
/opt/python/cp27-cp27m/bin/virtualenv /py36   --python=/opt/python/cp36-cp36m/bin/python && \
/opt/python/cp27-cp27m/bin/virtualenv /py37   --python=/opt/python/cp37-cp37m/bin/python

COMMENT(#,Install pip packages needed)
RUN \
/py27/bin/pip install cython && \
/py27mu/bin/pip install cython && \
/py34/bin/pip install cython && \
/py35/bin/pip install cython && \
/py36/bin/pip install cython && \
/py37/bin/pip install cython
