#define COMMENT(hash,input)hash input

COMMENT(#,Define an image to build most of the 64bit CoolProp wrappers on the Linux platform)
FROM coolprop/slavepython


#include "../buildsteps/docker.maintainer.txt"


#include "../buildsteps/docker.user.root.txt"


COMMENT(#,Install system tools for compilation of Python extensions numpy-scipy-pandas-matplotlib and the source code docs.)
#include "../buildsteps/apt-get.start.txt"
build-essential git gcc gfortran cmake python-dev p7zip \
cython python-matplotlib python-pandas \
swig octave liboctave-dev \
swig mono-mcs mono-runtime \
r-base-dev scilab julia && \\

#include "../buildsteps/apt-get.stop.txt"


#include "../buildsteps/docker.user.bot.txt"


COMMENT(#,Install emscripten distribution including LLVM)
RUN curl -o emscripten.tar.gz "https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz" && \
tar -xvf emscripten.tar.gz && rm emscripten.tar.gz

RUN pushd emsdk_portable && ./emsdk update && \
./emsdk install clang-master-64bit && \
./emsdk install emscripten-master-64bit && \
./emsdk install sdk-master-64bit && \
popd

RUN pushd emsdk_portable && ./emsdk activate latest && \
echo "$PWD/emsdk activate latest" >> /home/buildbot/.bash_profile && \
echo "source $PWD/emsdk_env.sh" >> /home/buildbot/.bash_profile && \
popd 

COMMENT(#,Some commercial wrappers are missing - Mathematica - MATLAB)
