notifications:
  email:
    on_success: never
    on_failure: change

sudo: required

services:
  - docker

before_install:
  - make clean

install:
  - make debian-build
  - make manylinux-build

#script: 
#  - make full-release

deploy:
  - provider: script
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && make full-push
    on:
      branch: master
  - provider: script
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && make full-push
    on:
      tags: true
