notifications:
  email:
    on_success: never
    on_failure: change

sudo: required

services:
  - docker

stages:
  - build
  - name: deploy
    if: tag = true
    #if: branch = master OR tag = true

jobs:
  include:
    - stage: build
      script: make clean && make full-release
    - stage: deploy
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && make full-push
