#include "../buildsteps/base.txt"

COMMENT(#,Define an image for CoolProp Python buildslaves)
FROM coolprop/workerbase:TAG


#include "../buildsteps/docker.maintainer.txt"



#include "../buildsteps/docker.user.root.txt"


COMMENT(#,Install system tools for compilation of Python extensions numpy-scipy-pandas)
#include "../buildsteps/apt-get.start.txt"
build-essential gcc python-dev \
libhdf5-serial-dev libnetcdf-dev liblapack-dev libatlas-dev libblas-dev && \\

#include "../buildsteps/apt-get.stop.txt"


#include "../buildsteps/docker.user.bot.txt"


COMMENT(#,Install miniconda Python distribution)
RUN curl -o miniconda.sh "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" && \
chmod +x miniconda.sh && linux64 ./miniconda.sh -b && rm miniconda.sh && \
echo "export PATH=/home/buildbot/miniconda3/bin:/home/buildbot/miniconda2/bin:$PATH" >> /home/buildbot/.bash_profile
ENV PATH /home/buildbot/miniconda3/bin:/home/buildbot/miniconda2/bin:$PATH

COMMENT(#,Add the miniconda environments for the Python builds)
RUN \
linux64 conda update conda && \
linux64 conda install conda-build && \
linux64 conda create -n CoolProp27 python=2.7 cython pip requests jinja2 pyyaml pycrypto numpy scipy matplotlib pandas wheel && \
linux64 conda create -n CoolProp36 python=3.6 cython pip requests jinja2 pyyaml pycrypto numpy scipy matplotlib pandas wheel && \
linux64 conda create -n CoolProp37 python=3.7 cython pip requests jinja2 pyyaml pycrypto numpy scipy matplotlib pandas wheel && \
linux64 conda create -n CoolProp38 python=3.8 cython pip requests jinja2 pyyaml numpy scipy matplotlib pandas wheel && \
linux64 conda clean -yilts
