#include "../buildsteps/base.txt"

COMMENT(#,Define a base image for all CoolProp buildslave images)
FROM coolprop/basesystem:VERSION


#include "../buildsteps/docker.maintainer.txt"


#include "../buildsteps/docker.user.root.txt"


RUN linux64 pip install buildbot-slave

COMMENT(#,Install the buildbot slave software and add the appropriate user)
RUN groupadd -r buildbot && useradd -r -d /home/buildbot -m -s /bin/bash -g buildbot buildbot

#include "../buildsteps/docker.user.bot.txt"


COMMENT(#,Add the entrypoint that creates a repository on first launch)
COPY ./entrypoint.sh /
ENTRYPOINT ["linux64", "/entrypoint.sh"]
