#define COMMENT(hash,input)hash input

COMMENT(#,Define an image for CoolProp Python buildslaves)
FROM coolprop/slavebase


#include "../buildsteps/docker.maintainer.txt"



#include "../buildsteps/docker.user.root.txt"


COMMENT(#,Install system tools for compilation of Python extensions numpy-scipy-pandas)
#include "../buildsteps/apt-get.start.txt"
build-essential gcc python-dev \
libhdf5-serial-dev libnetcdf-dev liblapack-dev libatlas-dev libblas-dev && \\

#include "../buildsteps/apt-get.stop.txt"


#include "../buildsteps/docker.user.bot.txt"


COMMENT(#,Install miniconda Python distribution)
RUN curl -o miniconda.sh "http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh" && \
chmod +x miniconda.sh && ./miniconda.sh -b && rm miniconda.sh && \
echo "export PATH=/home/buildbot/miniconda3/bin:/home/buildbot/miniconda2/bin:$PATH" >> /home/buildbot/.bash_profile
ENV PATH /home/buildbot/miniconda3/bin:/home/buildbot/miniconda2/bin:$PATH

COMMENT(#,Add the miniconda environments for the Python builds)
RUN \
conda install conda-build && \
conda create -n CoolProp27 python=2.7 cython pip requests jinja2 pyyaml pycrypto numpy scipy matplotlib pandas wheel && \
conda create -n CoolProp33 python=3.3 cython pip requests jinja2 pyyaml pycrypto numpy scipy matplotlib pandas wheel && \
conda create -n CoolProp34 python=3.4 cython pip requests jinja2 pyyaml pycrypto numpy scipy matplotlib pandas wheel && \
conda clean -yilts
