#define COMMENT(hash,input)hash input

COMMENT(#,Define an image to build the CoolProp documentation)
FROM coolprop/slavebase


#include "../buildsteps/docker.maintainer.txt"



#include "../buildsteps/docker.user.root.txt"


COMMENT(#,Install system tools for compilation of Python extensions numpy-scipy-pandas-matplotlib and the source code docs.)
#include "../buildsteps/apt-get.start.txt"
build-essential git gcc gfortran cmake python-dev \
libhdf5-serial-dev libnetcdf-dev \
libxml2-dev libxslt1-dev libxslt1.1 doxygen libtool \
libatlas3-base libblas3 liblapack3 \
libatlas-dev libblas-dev liblapack-dev \
libpng-dev tk libfreetype6-dev && \\


#include "../buildsteps/apt-get.stop.txt"


#include "../buildsteps/docker.user.bot.txt"


COMMENT(#,Install miniconda Python distribution)
RUN curl -o miniconda.sh "http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh" && \
chmod +x miniconda.sh && ./miniconda.sh -b && rm miniconda.sh && \
echo "export PATH=/home/buildbot/miniconda3/bin:/home/buildbot/miniconda2/bin:$PATH" >> /home/buildbot/.bash_profile
ENV PATH /home/buildbot/miniconda3/bin:/home/buildbot/miniconda2/bin:$PATH

COMMENT(#,Add the additional packages to the conda environment)
RUN \
conda install conda-build && \
conda create -n CoolPropWeb python=2.7 setuptools requests cython numpy scipy matplotlib pandas ipython wxpython && \
conda clean -yilts

COMMENT(#,Add some pip packages that only exist there)
RUN \
source activate CoolPropWeb && \
pip install sphinx cloud-sptheme sphinxcontrib-bibtex sphinxcontrib-doxylink sphinxcontrib-napoleon && \
source deactivate 
