
#define COMMENT(hash, input)hash input

COMMENT(#,Define a base image and provide a tag for it, default is latest)
FROM ubuntu:latest
MAINTAINER me

#include "../buildsteps/apt-get.start.txt"
#include "../buildsteps/apt-get.install.devtools.txt"
#include "../buildsteps/apt-get.stop.txt"