#include "../buildsteps/base.txt"

COMMENT(#,Define a base image for all 64bit CoolProp docker images)
FROM coolprop/debian:TAG

#include "../buildsteps/docker.maintainer.txt"


COMMENT(#,Make sure bash is the standard shell)
RUN rm /bin/sh && ln -sf /bin/bash /bin/sh

COMMENT(#,Install the development packages and compilers)
#include "../buildsteps/apt-get.start.txt"
build-essential gfortran gcc cmake git \
bash rsync curl wget nano \
python-dev python-pip && \\

#include "../buildsteps/apt-get.stop.txt"


COMMENT(#,Add some standard host keys)
RUN \
mkdir ${HOME}/.ssh && \
ssh-keyscan github.com >> ${HOME}/.ssh/known_hosts && \
ssh-keyscan gitlab.com >> ${HOME}/.ssh/known_hosts && \
ssh-keyscan bitbucket.org >> ${HOME}/.ssh/known_hosts && \
ssh-keyscan coolprop.org >> ${HOME}/.ssh/known_hosts && \
ssh-keyscan coolprop.dreamhosters.com >> ${HOME}/.ssh/known_hosts && \
cat ${HOME}/.ssh/known_hosts


COMMENT(#,Add the entrypoint)
ENTRYPOINT ["linux64", "/bin/sh"]
